export const sceneIds = {
    admin: {
        SCENE_ADD_PHRASE: 'SCENE_ADD_PHRASE',
        SCENE_ADD_CHANNEL: 'SCENE_ADD_CHANNEL',
        SCENE_DELETE_CHANNEL: 'SCENE_DELETE_CHANNEL',
        SCENE_ADD_MEDIA: 'SCENE_ADD_MEDIA',
        SCENE_MAILING: 'SCENE_MAILING',
        SCENE_ADD_DISCOUNT: 'SCENE_ADD_DISCOUNT',
        SCENE_ADD_BONUS: 'SCENE_ADD_BONUS',
        SCENE_ADD_REF_BONUS: 'SCENE_ADD_REF_BONUS',
        SCENE_ADD_REVIEW_URL: 'SCENE_ADD_REVIEW_URL',
        SCENE_ADD_REFERRAL: 'SCENE_ADD_REFERRAL',
        SCENE_ADD_REFERRAL_COUNT: 'SCENE_ADD_REFERRAL_COUNT',
        SCENE_CANCEL_BONUSES: 'SCENE_CANCEL_BONUSES',
        SCENE_ADD_ADMIN: 'SCENE_ADD_ADMIN',
        SCENE_ADD_PRODUCT: 'SCENE_ADD_PRODUCT',
        SCENE_EDIT_PRODUCT: 'SCENE_EDIT_PRODUCT',
    },
    user: {
        SCENE_ADD_AGE: 'SCENE_ADD_AGE',
        SCENE_GET_BONUS: 'SCENE_GET_BONUS',
    },
    payment: {
        SCENE_TARIFF_PLAN: 'SCENE_TARIFF_PLAN',
    }
}
